[package]
name = "bevy_easy_localize"
version = "0.1.0"
edition = "2021"

license-file = "LICENSE.txt"
description = "Lightweight bevy localization"
homepage = "https://github.com/0crispy/bevy_easy_localize"
repository = "https://github.com/0crispy/bevy_easy_localize"
readme = "README.md"

[dependencies]
bevy = "0.9"
csv = "1.1"
serde = "1.0"
